### ISSUE TITLE
unable to install plugins using doc information

### ISSUE THREAD

**Issue by frederic-joventures** [sensu-plugins/documentation#2]
/opt/sensu/embedded/bin/gem install sensu-plugin-disk-checks
ERROR:  Could not find a valid gem 'sensu-plugin-disk-checks' (>= 0) in any repository

**Comment by frederic-joventures** [comment]
closed it by mistake

**Comment by mattyjones** [comment]
@frederic-jomedia  

[sensu-plugins-disk-checks](https://rubygems.org/gems/sensu-plugins-disk-checks)
How to [install](https://github.com/sensu-plugins/documentation/blob/master/user_docs/installation_instructions.md) a sensu-plugin.

The issue you are having is that that gem is in a prerelease state, defined by the alpha tag.  You will need to use a prerelease flag in order to reach it and Rubygems does not index them in the same manner as other gems.

To check if it has an alpha tag check [here](https://rubygems.org/search?utf8=%E2%9C%93&query=sensu-plugins)  The alpha tags should be gone on most gems but next week.

**Comment by frederic-joventures** [comment]
@mattyjones  Tx I will wait for next week to test these new plugins
